---
- name: Verify Network Automation EE 1.1
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Find socat
      ansible.builtin.command:
        cmd: sh -c 'command -v socat'
      register: socat_path
      changed_when: false

    - name: Show socat path
      ansible.builtin.debug:
        var: socat_path.stdout

    - name: Show socat version
      ansible.builtin.command:
        cmd: socat -V
      register: socat_version
      changed_when: false

    - name: Display socat version
      ansible.builtin.debug:
        var: socat_version.stdout_lines
