---
- name: AAP notifier test
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Confirm successful notifier test
      ansible.builtin.debug:
        msg: "AAP NOTIFIER TEST ✅"
